name: CD Deployment

on:
  workflow_call:
    secrets:
      SERVER_HOST:
        required: true
      SERVER_USER:
        required: true
      SERVER_PASSWORD:
        required: true

jobs:
  deployment:
    name: Deploy to production
    runs-on: ubuntu_latest
    steps:
      # nanti stepsnya di sini